name: wallet_core
author: Lior Rabin <lior9586@gmail.com>
version: 0.0.1+14
homepage: https://github.com/fuseio/wallet_core
description: Fuse wallet core Dart library to interact with Etherum based networks and APIs.
environment: 
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies: 
  bip32: ^1.0.5
  bip39: ^1.0.3
  hex: ^0.1.2
  http: ^0.12.0
  resource: ^2.1.6
  web3dart: ^1.2.1
  flutter: 
    sdk: flutter
